accounts/urls.py
from django.urls import path, include

from accounts.views import custom_login, signup


urlpatterns = [
    path("login/", custom_login, name="login"),
    path("signup/", signup, name="signup"),
    path("", include("django.contrib.auth.urls")),
]

app_name = "accounts"

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("spa_comments.urls", namespace="spa-comments")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path('captcha/', include('captcha.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spa_comments/urls.py
from django.urls import path

from spa_comments.views import (
    CommentCreateView,
    CommentListView,
)

urlpatterns = [
    path("", CommentListView.as_view(), name="home"),
    path("comments/create/", CommentCreateView.as_view(), name="comment-create"),
    path("comments/<int:pk>/reply/", CommentCreateView.as_view(), name="comment-reply"),
    path("comments/my/", CommentListView.as_view(), name="comment-my"),

]

app_name = "spa-comments"

templates/includes/comment_list.html
{% load get_reply_list %}
<div class="post-preview" style="margin-left: 6%; font-size: 95%;">
  {% for reply in replies %}
    <div style="background-color: #fafff3">
      <p class="post-meta" style="background-color: #f8f9fa">
        <strong>{{ reply.author.username|capfirst }}</strong> at {{ reply.published_at }}
        <a href="{% url 'spa-comments:comment-reply' pk=reply.id %}" style="float: right; text-decoration: none">
          Reply<i class="fa-solid fa-reply"></i>
        </a>
      </p>
      <p class="post-title" style="padding-left: 5px">{{ reply.text|capfirst }}</p>
      {% if reply.image or reply.file %}
        <p class="post-meta" style="padding-left: 5px">Attachments:
          {% if reply.image %}
            <a href="{{ reply.image.url }}" target="_blank">
              <i class="fa-solid fa-file-image"></i>
            </a>
          {% endif %}
          {% if reply.file %}
            <a href="{{ reply.file.url }}" target="_blank">
              <i class="fa-solid fa-file-lines"></i>
            </a>
          {% endif %}
        </p>
      {% endif %}
      <!-- Divider-->
      <hr class="my-4"/>
    </div>
    {% get_reply_list reply comments_cache as replies %}
    {% if replies %}
      <div class="container">
        <p class="post-meta" style="background-color: #f8f9fa; font-size: 90%">
          Replies:
          <button style="float: right; background: none; border: none" onclick="toggleContainer(this)"><i
              class='fa-solid fa-minus'></i></button>
        </p>
        <div class="reply-container" style="display: block">
          {% include "includes/comment_list.html" with replies=replies %}
        </div>
      </div>
    {% endif %}
  {% endfor %}

</div>

templates/includes/footer.html
<footer class="border-top">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <ul class="list-inline text-center">
        <li class="list-inline-item">
          <a href="https://djinni.co/q/049fe6e507/">
              <span class="fa-stack fa-lg">
                <svg class="svg-inline--fa fa-circle fa-stack-2x" aria-hidden="true"
                     focusable="false" data-prefix="fas" data-icon="circle" role="img"
                     xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path
                    fill="currentColor"
                    d="M256 512c141.4 0 256-114.6 256-256S397.4 0 256 0S0 114.6 0 256S114.6 512 256 512z"></path></svg>
                <!-- <i class="fas fa-circle fa-stack-2x"></i> Font Awesome fontawesome.com -->
                <svg class="svg-inline--fa fa-twitter fa-stack-1x fa-inverse" aria-hidden="true"
                     focusable="false" data-prefix="fab" data-icon="twitter" role="img" fill="white"
                     xmlns="http://www.w3.org/2000/svg" height="16" width="16" viewBox="0 0 512 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2023 Fonticons, Inc.--><path
                    d="M184 48H328c4.4 0 8 3.6 8 8V96H176V56c0-4.4 3.6-8 8-8zm-56 8V96H64C28.7 96 0 124.7 0 160v96H192 320 512V160c0-35.3-28.7-64-64-64H384V56c0-30.9-25.1-56-56-56H184c-30.9 0-56 25.1-56 56zM512 288H320v32c0 17.7-14.3 32-32 32H224c-17.7 0-32-14.3-32-32V288H0V416c0 35.3 28.7 64 64 64H448c35.3 0 64-28.7 64-64V288z"></path></svg>
              </span>
          </a>
        </li>
        <li class="list-inline-item">
          <a href="https://www.linkedin.com/in/mrivankiv/">
            <span class="fa-stack fa-lg">
              <svg class="svg-inline--fa fa-circle fa-stack-2x" aria-hidden="true"
                   focusable="false" data-prefix="fas" data-icon="circle" role="img"
                   xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path
                  fill="currentColor"
                  d="M256 512c141.4 0 256-114.6 256-256S397.4 0 256 0S0 114.6 0 256S114.6 512 256 512z"></path></svg>
              <!-- <i class="fas fa-circle fa-stack-2x"></i> Font Awesome fontawesome.com -->
                <svg class="svg-inline--fa fa-linkedin-l fa-stack-1x fa-inverse"
                     aria-hidden="true" focusable="false" data-prefix="fab"
                     data-icon="linkedin-l" role="img" xmlns="http://www.w3.org/2000/svg" height="14" width="12.25"
                     fill="white"
                     viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2023 Fonticons, Inc.--><path
                    d="M416 32H31.9C14.3 32 0 46.5 0 64.3v383.4C0 465.5 14.3 480 31.9 480H416c17.6 0 32-14.5 32-32.3V64.3c0-17.8-14.4-32.3-32-32.3zM135.4 416H69V202.2h66.5V416zm-33.2-243c-21.3 0-38.5-17.3-38.5-38.5S80.9 96 102.2 96c21.2 0 38.5 17.3 38.5 38.5 0 21.3-17.2 38.5-38.5 38.5zm282.1 243h-66.4V312c0-24.8-.5-56.7-34.5-56.7-34.6 0-39.9 27-39.9 54.9V416h-66.4V202.2h63.7v29.2h.9c8.9-16.8 30.6-34.5 62.9-34.5 67.2 0 79.7 44.3 79.7 101.9V416z"></path></svg>
            </span>
          </a>
        </li>
        <li class="list-inline-item">
          <a href="https://github.com/Naz-iv">
              <span class="fa-stack fa-lg">
                <svg class="svg-inline--fa fa-circle fa-stack-2x" aria-hidden="true"
                     focusable="false" data-prefix="fas" data-icon="circle" role="img"
                     xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path
                    fill="currentColor"
                    d="M256 512c141.4 0 256-114.6 256-256S397.4 0 256 0S0 114.6 0 256S114.6 512 256 512z"></path></svg>
                <!-- <i class="fas fa-circle fa-stack-2x"></i> Font Awesome fontawesome.com -->
                <svg class="svg-inline--fa fa-github fa-stack-1x fa-inverse" aria-hidden="true"
                     focusable="false" data-prefix="fab" data-icon="github" role="img"
                     xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512" data-fa-i2svg=""><path
                    fill="currentColor"
                    d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"></path></svg>
                <!-- <i class="fab fa-github fa-stack-1x fa-inverse"></i> Font Awesome fontawesome.com -->
              </span>
          </a>
        </li>
      </ul>
    </div>
  </div>
</footer>

templates/includes/header.html
{% load static %}
<header class="masthead" style="background-image: url('{% static "assets/img/home-bg.png" %}')">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>SPA Application</h1>
          <span class="subheading">Application to manage SPA reviews</span>
        </div>
      </div>
    </div>
  </div>
</header>

templates/includes/navigation.html
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
  <div class="container px-4 px-lg-5">
    <a class="navbar-brand" href="{% url 'spa-comments:home' %}">SPA App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ms-auto py-4 py-lg-0">
        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'spa-comments:home' %}">Home</a></li>
        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'spa-comments:comment-create' %}">Add Comment</a></li>
        {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'spa-comments:comment-my' %}">My Comments</a></li>
          <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'accounts:logout' %}">Logout</a></li>
        {% else %}
          <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'accounts:login' %}">Login</a></li>
        {% endif %}

      </ul>
    </div>
  </div>
</nav>

templates/includes/ordering.html
<form method="get" action="{% url 'spa-comments:home' %}">
  <label for="order_by">Order by:</label>
  <select name="order_by" id="order_by">
    <option value="-published_at" {% if user_choice == "-published_at" %}selected{% endif %}>Newest</option>
    <option value="published_at" {% if user_choice == "published_at" %}selected{% endif %}>Oldest</option>
    <option value="username" {% if user_choice == "username" %}selected{% endif %}>Username Ascending</option>
    <option value="-username" {% if user_choice == "-username" %}selected{% endif %}>Username Descending</option>
    <option value="email" {% if user_choice == "email" %}selected{% endif %}>Email Ascending</option>
    <option value="-email" {% if user_choice == "-email" %}selected{% endif %}>Email Descending</option>
  </select>
  <button type="submit" style="border: none; background-color: transparent"><i class="fa-solid fa-sort"></i></button>
</form>

templates/includes/pagination.html
{% load query_transformer %}
<div class="d-flex justify-content-end mb-4">
    <span class="btn btn-primary text-uppercase">
      {% if page_obj.has_previous %}

        <a href="?{% query_transform request page=1 %}">&laquo; first</a>
        <a href="?{% query_transform request page=page_obj.previous_page_number %}">previous</a>
      {% endif %}

      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

      {% if page_obj.has_next %}
        <a href="?{% query_transform request page=page_obj.next_page_number %}">next</a>
        <a href="?{% query_transform request page=page_obj.paginator.num_pages %}">last &raquo;</a>
      {% endif %}
    </span>
</div>