accounts/urls.py
from django.urls import path, include

from accounts.views import custom_login, signup


urlpatterns = [
    path("login/", custom_login, name="login"),
    path("signup/", signup, name="signup"),
    path("", include("django.contrib.auth.urls")),
]

app_name = "accounts"

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("spa_comments.urls", namespace="spa-comments")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path('captcha/', include('captcha.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spa_comments/urls.py
from django.urls import path

from spa_comments.views import (
    CommentCreateView,
    CommentListView,
)

urlpatterns = [
    path("", CommentListView.as_view(), name="home"),
    path("comments/create/", CommentCreateView.as_view(), name="comment-create"),
    path("comments/<int:pk>/reply/", CommentCreateView.as_view(), name="comment-reply"),
    path("comments/my/", CommentListView.as_view(), name="comment-my"),

]

app_name = "spa-comments"

spa_comments/models.py
import os
import re
import uuid

from PIL import Image
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator, FileExtensionValidator
from django.db import models

from collections import deque


class Author(models.Model):
    username = models.CharField(max_length=255)
    email = models.EmailField()
    user = models.OneToOneField(
        get_user_model(),
        on_delete=models.SET_NULL,
        null=True,
        default=None
    )

    def __str__(self):
        return self.username


def create_path_for_image(instance, filename: str):
    _, extension = os.path.splitext(filename)
    return os.path.join(
        "uploads/images/",
        f"image-{uuid.uuid4()}{extension}"
    )


def create_path_for_file(instance, filename: str):
    _, extension = os.path.splitext(filename)
    return os.path.join(
        "uploads/files/",
        f"file-{uuid.uuid4()}{extension}"
    )

def validate_file_size(file):
    max_size = 100 * 1024
    if file.size > max_size:
        raise ValidationError("File size must be less than 100 KB.")


class Comment(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name="comments")
    published_at = models.DateTimeField(auto_now_add=True)
    text = models.TextField(validators=[MinLengthValidator(1)])
    parent_comment = models.ForeignKey(
        "Comment", on_delete=models.SET_NULL, null=True, blank=True, related_name="replies"
    )
    image = models.ImageField(
        null=True, blank=True,
        validators=[FileExtensionValidator(allowed_extensions=["jpg", "gif", "png"])],
        upload_to=create_path_for_image
    )
    file = models.FileField(
        null=True, blank=True,
        validators=[FileExtensionValidator(allowed_extensions=["txt"]), validate_file_size],
        upload_to=create_path_for_file
    )

    class Meta:
        ordering = ['-published_at']

    def clean(self):
        super().clean()

        allowed_tags = (
            "<a>", "</a>", "<code>", "</code>", "<i>", "</i>", "<strong>", "</strong>"
        )

        tags_deque = deque()

        tags = re.findall(r"<[^>]*>", self.text)

        for tag in tags:
            if "/" not in tag:
                if tag.startswith("<a "):
                    tag = tag.split()[0] + ">"
                tags_deque.append(tag)
            else:
                if not tags_deque:
                    raise ValidationError("Closed tags must match opening tags!")

                if tag not in allowed_tags:
                    raise ValidationError(
                        "Unsupported HTML tag used! Only following HTML tags are allowed: "
                        "<a></a>, <code></code>, <i></i>, <strong></strong>"
                    )

                opening_tag = tags_deque.pop()
                if opening_tag[1:] != tag[2:]:
                    raise ValidationError("Opening tags must match closing tags!")

        if len(tags_deque) != 0:
            raise ValidationError("All opened HTML tags must be closed!")

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

        if self.image:
            img = Image.open(self.image.path)
            max_size = (320, 240)
            img.thumbnail(max_size)
            img.save(self.image.path)

    def __str__(self):
        formatted_time = self.published_at.strftime("%H:%M:%S %d-%m-%Y")
        return f"Comment by {self.author} at {formatted_time}"

templates/comments_create.html
{% extends "index.html" %}
{% load static %}
{% block header %}
  <!-- Page Header-->
  <header class="masthead" style="background-image: url('{% static "assets/img/create-bg.png" %}')">
    <div class="container position-relative px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <div class="page-heading">
            <h1>Add Comment</h1>
            <span class="subheading">Please write your comment below</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

{% block main_content %}
  <!-- Main Content-->
  <main class="mb-4">
    <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <div class="my-5">
            <form method="post" action="{% url 'spa-comments:comment-create' %}"
                  enctype="multipart/form-data" novalidate>
              {% csrf_token %}
              {{ form.non_field_errors }}

              {% if form.errors %}
                <div class="text-left text-danger mb-2">
                  {% for key, value in form.errors.items %}
                    {{ key|capfirst }} {{ value }}
                  {% endfor %}
                </div>
              {% endif %}

              {% for field in form %}
                <br>
                {% if field.label == "Captcha" %}
                  {{ field.help_text }}
                  <br>
                  <br>
                  {{ field }}
                  <br>
                {% else %}
                  <div class="form-floating">
                    {{ field }}
                    {% if field.label != "Text" and field.label != "Parent ID"%}
                      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {% endif %}
                  </div>
                {% endif %}
              {% endfor %}

              <br/>

              <!-- Submit Button-->
              <button class="btn btn-primary text-uppercase" id="submitButton" type="submit">Send</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

templates/index.html
<!DOCTYPE html>
{% load static %}
{% load get_reply_list %}
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
  <meta name="description" content="Service for managing customers comments of SPA centre"/>
  <meta name="author" content="mr.nivankiv@gmail.com"/>
  <title>Clean Blog - Start Bootstrap Theme</title>
  <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
  <!-- Font Awesome icons (free version)-->
  <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
  <!-- Google fonts-->
  <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet"
        type="text/css"/>
  <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
      rel="stylesheet" type="text/css"/>
  <!-- Core theme CSS (includes Bootstrap)-->
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
{% block navigation %}
  {% include "includes/navigation.html" %}
{% endblock %}

{% block header %}
  {% include "includes/header.html" %}
{% endblock %}

{% block main_content %}
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div style="padding-top: 16px; padding-bottom: 16px; background-color: #fff;">
          {% include "includes/ordering.html" %}
        </div>
        <!-- Post preview-->
        <div class="post-preview">
          {% for comment in comments %}
            <div style="background-color: #fff6f2">
              <p class="post-meta" style="background-color: #f8f9fa;">
                <strong>{{ comment.author.username|capfirst }}</strong> at {{ comment.published_at }}
                <a href="{% url 'spa-comments:comment-reply' pk=comment.id %}"
                   style="float: right; text-decoration: none">
                  Reply<i class="fa-solid fa-reply"></i>
                </a>
              </p>
              <p class="post-title " style="padding-left: 5px">{{ comment.text|capfirst }}</p>
              {% if comment.image or comment.file %}
                <p class="post-meta" style="padding-left: 5px">Attachments:
                  {% if comment.image %}
                    <a href="{{ comment.image.url }}" target="_blank">
                      <i class="fa-solid fa-file-image"></i>
                    </a>
                  {% endif %}
                  {% if comment.file %}
                    <a href="{{ comment.file.url }}" target="_blank">
                      <i class="fa-solid fa-file-lines"></i>
                    </a>
                  {% endif %}
                </p>
              {% endif %}
              <!-- Divider-->
              <hr class="my-4"/>
            </div>
            {% get_reply_list comment comments_cache as replies %}
            {% if replies %}
              <div class="container">
                <p class="post-meta" style="background-color: #f8f9fa; font-size: 90%">
                  Replies:
                  <button style="float: right; background: none; border: none" onclick="toggleContainer(this)"><i
                      class='fa-solid fa-minus'></i></button>
                </p>
                <div class="reply-container" style="display: block">
                  {% include "includes/comment_list.html" with replies=replies %}
                </div>
              </div>
            {% endif %}
          {% endfor %}
        </div>

        <!-- Pagination-->
        {% include "includes/pagination.html" %}

      </div>
    </div>
  </div>
{% endblock %}

{% block footer %}
  {% include "includes/footer.html" %}
{% endblock %}

<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/scripts.js' %}"></script>

<script>
    function toggleContainer(button) {
        var container = button.closest(".container");

        var replyContainer = container.querySelector(".reply-container");

        if (replyContainer.style.display === "none" || replyContainer.style.display === "") {
            replyContainer.style.display = "block";
            button.innerHTML = "<i class='fa-solid fa-minus'></i>";
        } else {
            replyContainer.style.display = "none";
            button.innerHTML = "<i class='fa-solid fa-plus'></i>";
        }
    }
</script>
</body>
</html>

templates/login.html
{% extends "index.html" %}
{% load static %}
{% block header %}
  <!-- Page Header-->
  <header class="masthead" style="background-image: url('{% static "assets/img/contact-bg.jpg" %}')">
    <div class="container position-relative px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <div class="page-heading">
            <h1>Login</h1>
            <span class="subheading">Please log in to get access to extended functionality<br>
              or <a href="{% url 'spa-comments:signup' %}" class="text-bg-primary"><strong>SignUp</strong></a>, if you don't have account yet.
            </span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

{% block main_content %}
  <!-- Main Content-->
  <main class="mb-4">
    <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <div class="my-5">
            <form method="post" id="form">
              {% csrf_token %}
              {{ form.non_field_errors }}

              {% for field in form %}
                <div class="form-floating">
                  {{ field }}
                  <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                  <div class="invalid-feedback"
                       data-sb-feedback="{{ field.id_for_label }}:required">{{ field.errors }}</div>
                </div>
              {% endfor %}

              <br/>

              <!-- Submit success message -->
              <div class="d-none" id="submitSuccessMessage">
                <div class="text-center mb-3">
                  <div class="fw-bolder">Form submission successful!</div>
                  To activate this form, sign up at
                  <br/>
                  <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                </div>
              </div>

              <!-- Submit error message -->
              <div class="d-none" id="submitErrorMessage">
                <div class="text-center text-danger mb-3">Error sending message!</div>
              </div>

              <!-- Submit Button-->
              <button class="btn btn-primary text-uppercase disabled" id="submitButton" type="submit">Send</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

templates/signup.html
{% extends "index.html" %}
{% load static %}
{% block header %}
  <!-- Page Header-->
  <header class="masthead" style="background-image: url('{% static "assets/img/contact-bg.jpg" %}')">
    <div class="container position-relative px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <div class="page-heading">
            <h1>Sign Up</h1>
            <span class="subheading">Create account to get access to extended functionality<br>
              or <a href="{% url 'spa-comments:login' %}" class="text-bg-primary"><strong>Login</strong></a>, if you already have account.
            </span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

{% block main_content %}
  <!-- Main Content-->
  <main class="mb-4">
    <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <div class="my-5">
            <form method="post" id="form">
              {% csrf_token %}
              {{ form.non_field_errors }}

              {% for field in form %}
                <div class="form-floating">
                  {{ field }}
                  <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                  <div class="invalid-feedback"
                       data-sb-feedback="{{ field.id_for_label }}:required">{{ field.errors }}</div>
                </div>
              {% endfor %}

              <br/>

              <!-- Submit success message -->
              <div class="d-none" id="submitSuccessMessage">
                <div class="text-center mb-3">
                  <div class="fw-bolder">Form submission successful!</div>
                  To activate this form, sign up at
                  <br/>
                  <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                </div>
              </div>

              <!-- Submit error message -->
              <div class="d-none" id="submitErrorMessage">
                <div class="text-center text-danger mb-3">Error sending message!</div>
              </div>

              <!-- Submit Button-->
              <button class="btn btn-primary text-uppercase disabled" id="submitButton" type="submit">Send</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}